name: project_bills
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
#  Date Field
  date_field: ^6.0.0
  # Intl is a set of packages that provide internationalization and localization
  intl:
#  State Management
  flutter_bloc:
  bloc:
#  bottomNavBar
  google_nav_bar: ^5.0.6
#  Draw Analysis charts
  fl_chart: ^0.70.1
#  app_resources:
# AweSome For Dialog
  awesome_dialog: ^3.2.1
#  Add Image
  image_picker: ^1.1.2
    # URL Launcher
  url_launcher:
  eva_icons_flutter:

  math_expressions:
#  View Table
  data_table_2: ^2.5.18
  scrollable_table_view: ^2.0.3
  flutter_tesseract_ocr: ^0.4.28
  google_ml_kit: ^0.19.0
#  flutter_mobile_vision_2:
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  #  Toast Library for Flutter, Easily create toast messages in single line of code
  fluttertoast: ^8.2.12
  #    A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/tessdata/
    - assets/tessdata/eng.traineddata
    - assets/tessdata/ara.traineddata
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Tajawal
      fonts:
        # - asset: assets/fonts/Tajawal-Bold.ttf
        # - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf

